@hostname = 127.0.0.1
@port = 8000

###

POST http://{{hostname}}:{{port}}/watching HTTP/1.1
Content-Type: application/json
Cookie: user_id=bda031c0-4e7d-493a-92ba-6fc1eb3e6216

{
    "video_id": "123",
    "position": 1
}

###

GET http://{{hostname}}:{{port}}/watching?video_id=123 HTTP/1.1
Content-Type: application/json
Cookie: user_id=bda031c0-4e7d-493a-92ba-6fc1eb3e6216
